[package]
name = "blobby-test"
version = "0.1.0"
authors = [ "wasmCloud Team" ]
edition = "2021"

[dependencies]
serde_json = "1.0.85"
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
tempfile = "3"
